# Generated by Django 5.0.7 on 2024-08-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
